name: Create Addon Release

on:
  push:
    tags:
      - "v*" # Triggers on version tags like v1.0, v1.1, etc.
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create addon directory structure
        run: |
          mkdir -p WarbandBankFilter

      - name: Copy addon files
        run: |
          cp WarbandBankFilter.toc WarbandBankFilter/
          cp WarbandBankFilter.lua WarbandBankFilter/
          cp LICENSE WarbandBankFilter/

      - name: Create zip file
        run: |
          zip -r WarbandBankFilter.zip WarbandBankFilter/

      - name: Get version from tag
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="manual-$(date +%Y%m%d-%H%M%S)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: WarbandBankFilter ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## Installation
            1. Download the `WarbandBankFilter.zip` file
            2. Extract it to your World of Warcraft `Interface/AddOns/` directory
            3. Restart World of Warcraft or reload UI with `/reload`

            ## Changes
            See commit history for detailed changes in this release.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./WarbandBankFilter.zip
          asset_name: WarbandBankFilter.zip
          asset_content_type: application/zip

      - name: Upload artifact (for manual runs)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: WarbandBankFilter-${{ steps.get_version.outputs.VERSION }}
          path: WarbandBankFilter.zip
